### ISSUE TITLE
Consider bumping minimum supported `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [shinnn/output-file-sync#1]
If you require at least `node>=4`, you can drop the `object-assign` dependency.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for your time.

**Comment by shinnn** [comment]
No problem! Thanks for your suggestion.

Please wait a little for the v2.0.0 release.

**Comment by shinnn** [comment]
Published v2.0.0. https://github.com/shinnn/output-file-sync/releases/tag/v2.0.0
